Cleaning Data

In [1]:
import pandas as pd
import numpy as np

In [5]:
# Load data into pandas df
df_wc = pd.read_csv('worldcitiespop.csv')
df_cc = pd.read_csv('country_codes.csv')

df_wc.head()

C:\Users\travd\AppData\Local\Temp\ipykernel_3008\3863641241.py:2: DtypeWarning: Columns (0: Region) have mixed types. Specify dtype option on import or set low_memory=False.
  df_wc = pd.read_csv('worldcitiespop.csv')

  Country        City  AccentCity Region  Population   Latitude  Longitude
0      ad       aixas       Aixàs    6.0         NaN  42.483333   1.466667
1      ad  aixirivali  Aixirivali    6.0         NaN  42.466667   1.500000
2      ad  aixirivall  Aixirivall    6.0         NaN  42.466667   1.500000
3      ad   aixirvall   Aixirvall    6.0         NaN  42.466667   1.500000
4      ad    aixovall    Aixovall    6.0         NaN  42.466667   1.483333

In [6]:
df_cc.head()

,name,alpha-2,alpha-3,country-code,iso_3166-2,region,sub-region,intermediate-region,region-code,sub-region-code,intermediate-region-code
0,Afghanistan,AF,AFG,4,ISO 3166-2:AF,Asia,Southern Asia,NaN,142.0,34.0,NaN
1,Åland Islands,AX,ALA,248,ISO 3166-2:AX,Europe,Northern Europe,NaN,150.0,154.0,NaN
2,Albania,AL,ALB,8,ISO 3166-2:AL,Europe,Southern Europe,NaN,150.0,39.0,NaN
3,Algeria,DZ,DZA,12,ISO 3166-2:DZ,Africa,Northern Africa,NaN,2.0,15.0,NaN
4,American Samoa,AS,ASM,16,ISO 3166-2:AS,Oceania,Polynesia,NaN,9.0,61.0,NaN

In [9]:
# Check missing values
print("Missing Latitudes: ", df_wc['Latitude'].isna().sum())
print("Missing Longitudes: ", df_wc['Longitude'].isna().sum())

Missing Latitudes:  0
Missing Longitudes:  0

In [16]:
# Check duplicates
print("Duplicate cities: ", df_wc.duplicated(subset=['City'], keep=False).sum())
#print("Duplicate Latitudes: ", df_wc['Latitude'].duplicated().sum())
#print("Duplicate Longitudes: ", df_wc['Longitude'].duplicated().sum())

Duplicate cities:  1135769

In [14]:
duplicates = df_wc[df_wc.duplicated(subset=['City'], keep=False)]
print(duplicates)

        Country        City  AccentCity Region  Population   Latitude  \
5            ad     andorra     Andorra    7.0         NaN  42.500000
13           ad       arans       Arans    4.0         NaN  42.583333
20           ad     canillo     Canillo    2.0      3292.0  42.566667
23           ad      certes      Certés    6.0         NaN  42.466667
25           ad      el pui      El Pui    4.0         NaN  42.550000
...         ...         ...         ...    ...         ...        ...
3173931      zw   woodville   Woodville      6         NaN -20.080000
3173932      zw  workington  Workington      4         NaN -17.848056
3173940      zw        zaka        Zaka      7         NaN -20.350000
3173943      zw       zandi       Zandi      6         NaN -19.183333
3173950      zw        ziga        Ziga      6         NaN -19.216667

         Longitude
5         1.516667
13        1.516667
20        1.600000
23        1.500000
25        1.516667
...            ...
3173931  28.658333
3173932  31.015000
3173940  31.450000
3173943  27.466667
3173950  27.483333

[1135769 rows x 7 columns]